# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.CharField(blank=True, max_length=20)),
                ('collection', models.CharField(blank=True, max_length=60, null=True)),
                ('arranger', models.CharField(blank=True, max_length=120, null=True)),
                ('editor', models.CharField(blank=True, max_length=120, null=True)),
                ('uniform_title', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.CharField(blank=True, max_length=120, null=True)),
                ('place_of_publication', models.CharField(blank=True, max_length=120, null=True)),
                ('date_of_publication', models.CharField(blank=True, max_length=120, null=True)),
                ('copyright_date', models.CharField(blank=True, max_length=120, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher_number', models.CharField(blank=True, max_length=120, null=True)),
                ('series', models.CharField(blank=True, max_length=20, null=True)),
                ('collation', models.CharField(blank=True, max_length=120, null=True)),
                ('holdings', models.CharField(blank=True, max_length=120, null=True)),
                ('medium', models.CharField(blank=True, max_length=120, null=True)),
                ('key_signature', models.CharField(blank=True, max_length=20, null=True)),
                ('condition', models.CharField(blank=True, max_length=20, null=True)),
                ('missing', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=20, null=True)),
                ('contents', models.CharField(blank=True, max_length=20, null=True)),
                ('cost', models.CharField(blank=True, max_length=20, null=True)),
                ('cat_date', models.CharField(blank=True, max_length=20, null=True)),
                ('cat_by', models.CharField(blank=True, max_length=20, null=True)),
                ('acquisition_date', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Enter a brief note', max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance_collection.Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ManyToManyField(to='performance_collection.Subject'),
        ),
    ]
