# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='performance_collection.Subject'),
        ),
    ]
