# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0002_auto_20180217_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
