# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0003_score_score_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='call_number',
        ),
    ]
