# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0004_remove_score_call_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='call_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
