# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0005_score_call_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.ManyToManyField(to='performance_collection.Subject'),
        ),
    ]
