# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0006_auto_20180219_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ForeignKey(default='Symphonies', on_delete=django.db.models.deletion.CASCADE, to='performance_collection.Subject'),
            preserve_default=False,
        ),
    ]
