# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0008_auto_20180219_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='series',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
