# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0009_auto_20180219_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
        migrations.AddField(
            model_name='score',
            name='subject',
            field=models.ManyToManyField(to='performance_collection.Subject'),
        ),
    ]
