# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance_collection', '0011_auto_20180219_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='term',
            new_name='author',
        ),
    ]
